# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b24150af8ca85ec216d9f59b134a6aa6181d04d1b34cc98886bcd0b0f899722265c572cbea06b9c8e08e0d7b6d23ba3877e23655d0618a2829fe13cd0c13d01d

test:
  secret_key_base: 195802a40879ace6d6d9774bd221f23ca4b0e914141d22c5265cc0ce4a075fd4c21d5355014337c67038c13f7baf44223fc555f836eaf62bd410cd86b5e753cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
